complete_subject = "ALM Notification: {0} list processed."
complete_message = """{requestor},

Your list attached to {object_name} has been processed. Below are the results of 
the program. All files generated by the search program that require 
further research, or that were requested, have been attached.

If you have questions, please reach out to:
{team}
{email}

Search results:
Total Advisors: {total}
Found in SF: {found}
Updating Contact in SF or Adding to Campaign: {updating}
Contact Info Up-To-Date: {not_updating}
Creating: {creating}
Added to {object}: {adding}
Updated in {object}: {stayed} 
Would remove from {object}: {remove}
Need research: {research}
Received: {received}
Process Started: {started}
Process Completed: {ended}
Processing Time: {duration}
"""
